spring:
  application:
    name: gatewaydemo
  cloud:
    gateway:
      routes:
        ###路由id
       # - id: hello-router
          ####转发http://www.gblfy.com/
       #   uri: http://localhost:8001/hello
          ###匹配规则
       #   predicates:
       #    - Path= /**
server:
  port: 8080